package com.yiminwu.mapper;

import java.io.Serializable;

public interface BaseMapper<T, PK extends Serializable> {
   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table classification
    *
    * @mbggenerated
    */
   int deleteByPrimaryKey(PK id);

   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table classification
    *
    * @mbggenerated
    */
   int insert(T record);

   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table classification
    *
    * @mbggenerated
    */
   int insertSelective(T record);

   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table classification
    *
    * @mbggenerated
    */
   T selectByPrimaryKey(PK id);

   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table classification
    *
    * @mbggenerated
    */
   int updateByPrimaryKeySelective(T record);

   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table classification
    *
    * @mbggenerated
    */
   int updateByPrimaryKey(T record);

}
