package com.yiminwu.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.yiminwu.model.LayoutGroupItem;

@Mapper
public interface LayoutGroupItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_group_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(LayoutGroupItem key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_group_item
     *
     * @mbggenerated
     */
    int insert(LayoutGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_group_item
     *
     * @mbggenerated
     */
    int insertSelective(LayoutGroupItem record);
}