package com.yiminwu.mapper;

import org.apache.ibatis.annotations.Mapper;
import com.yiminwu.model.LayoutItem;

@Mapper
public interface LayoutItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(LayoutItem key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_item
     *
     * @mbggenerated
     */
    int insert(LayoutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_item
     *
     * @mbggenerated
     */
    int insertSelective(LayoutItem record);
}