package com.yiminwu.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.yiminwu.model.ProductAttributeValue;
import com.yiminwu.model.ProductAttributeValueKey;

@Mapper
public interface ProductAttributeValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_value
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ProductAttributeValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_value
     *
     * @mbggenerated
     */
    int insert(ProductAttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_value
     *
     * @mbggenerated
     */
    int insertSelective(ProductAttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_value
     *
     * @mbggenerated
     */
    ProductAttributeValue selectByPrimaryKey(ProductAttributeValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductAttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductAttributeValue record);
}