package com.yiminwu.model;

import java.util.Date;

public class Img {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.FileName
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.Ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.Path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.Ext
     *
     * @mbggenerated
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.ImgSize
     *
     * @mbggenerated
     */
    private Long imgsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.Width
     *
     * @mbggenerated
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.Height
     *
     * @mbggenerated
     */
    private Integer height;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.Id
     *
     * @return the value of img.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.Id
     *
     * @param id the value for img.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.FileName
     *
     * @return the value of img.FileName
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.FileName
     *
     * @param filename the value for img.FileName
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.Ts
     *
     * @return the value of img.Ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.Ts
     *
     * @param ts the value for img.Ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.Path
     *
     * @return the value of img.Path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.Path
     *
     * @param path the value for img.Path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.Ext
     *
     * @return the value of img.Ext
     *
     * @mbggenerated
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.Ext
     *
     * @param ext the value for img.Ext
     *
     * @mbggenerated
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.ImgSize
     *
     * @return the value of img.ImgSize
     *
     * @mbggenerated
     */
    public Long getImgsize() {
        return imgsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.ImgSize
     *
     * @param imgsize the value for img.ImgSize
     *
     * @mbggenerated
     */
    public void setImgsize(Long imgsize) {
        this.imgsize = imgsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.Width
     *
     * @return the value of img.Width
     *
     * @mbggenerated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.Width
     *
     * @param width the value for img.Width
     *
     * @mbggenerated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.Height
     *
     * @return the value of img.Height
     *
     * @mbggenerated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.Height
     *
     * @param height the value for img.Height
     *
     * @mbggenerated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }
}