package com.yiminwu.model;

public class LayoutItem {
   
    public LayoutItem() {
       
    }
    
    public LayoutItem(Integer layoutid, Integer groupid) {
       this.layoutid = layoutid;
       this.groupid = groupid;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout_item.LayoutId
     *
     * @mbggenerated
     */
    private Integer layoutid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout_item.GroupId
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout_item.LayoutId
     *
     * @return the value of layout_item.LayoutId
     *
     * @mbggenerated
     */
    public Integer getLayoutid() {
        return layoutid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout_item.LayoutId
     *
     * @param layoutid the value for layout_item.LayoutId
     *
     * @mbggenerated
     */
    public void setLayoutid(Integer layoutid) {
        this.layoutid = layoutid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout_item.GroupId
     *
     * @return the value of layout_item.GroupId
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout_item.GroupId
     *
     * @param groupid the value for layout_item.GroupId
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }
}