package com.yiminwu.model;

public class LayoutGroupItem {
   
   public LayoutGroupItem() {
      
   }
   
   public LayoutGroupItem(Integer groupid, Long memberid, String membertype) {
      this.groupid = groupid;
      this.memberid = memberid;
      this.membertype = membertype;
      
   }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout_group_item.GroupId
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout_group_item.MemberId
     *
     * @mbggenerated
     */
    private Long memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout_group_item.MemberType
     *
     * @mbggenerated
     */
    private String membertype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout_group_item.GroupId
     *
     * @return the value of layout_group_item.GroupId
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout_group_item.GroupId
     *
     * @param groupid the value for layout_group_item.GroupId
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout_group_item.MemberId
     *
     * @return the value of layout_group_item.MemberId
     *
     * @mbggenerated
     */
    public Long getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout_group_item.MemberId
     *
     * @param memberid the value for layout_group_item.MemberId
     *
     * @mbggenerated
     */
    public void setMemberid(Long memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout_group_item.MemberType
     *
     * @return the value of layout_group_item.MemberType
     *
     * @mbggenerated
     */
    public String getMembertype() {
        return membertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout_group_item.MemberType
     *
     * @param membertype the value for layout_group_item.MemberType
     *
     * @mbggenerated
     */
    public void setMembertype(String membertype) {
        this.membertype = membertype == null ? null : membertype.trim();
    }
}