package com.yiminwu.model;

import java.io.Serializable;

public class LayoutGroup implements BaseObject{
   
    public static final String LINK_TYPE_PRODUCT = "Product";
    
    public static final String LINK_TYPE_CLASSIFICATION = "Classification";
    
    public static final String LINK_TYPE_BRAND = "Brand";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout_group.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout_group.Name
     *
     * @mbggenerated
     */
    private String name;
    
    
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout_group.LinkType
     *
     * @mbggenerated
     */
    private String linktype;
    
    
    private String linktypeDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout_group.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout_group.Id
     *
     * @return the value of layout_group.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout_group.Id
     *
     * @param id the value for layout_group.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout_group.Name
     *
     * @return the value of layout_group.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout_group.Name
     *
     * @param name the value for layout_group.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout_group.LinkType
     *
     * @return the value of layout_group.LinkType
     *
     * @mbggenerated
     */
    public String getLinktype() {
        return linktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout_group.LinkType
     *
     * @param linktype the value for layout_group.LinkType
     *
     * @mbggenerated
     */
    public void setLinktype(String linktype) {
        this.linktype = linktype == null ? null : linktype.trim();
        this.setLinktypeDisplay(LayoutGroup.LINK_TYPE_PRODUCT.equalsIgnoreCase(this.linktype) ? "产品" : 
           (LayoutGroup.LINK_TYPE_CLASSIFICATION.equalsIgnoreCase(this.linktype) ? "分类" : "品牌"));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout_group.Description
     *
     * @return the value of layout_group.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout_group.Description
     *
     * @param description the value for layout_group.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public Serializable getPK() {
       return id;
    }

    public String getLinktypeDisplay() {
       return linktypeDisplay;
    }

    public void setLinktypeDisplay(String linktypeDisplay) {
       this.linktypeDisplay = linktypeDisplay;
    }

   public String getImgurl() {
      return imgurl;
   }

   public void setImgurl(String imgurl) {
      this.imgurl = imgurl;
   }
}