package com.yiminwu.model;

import java.io.Serializable;

public class Layout implements BaseObject{
   
    public static final String SHOW_TYPE_CAROUSEL = "Carousel";
    
    public static final String SHOW_TYPE_ICONL = "Icon";
    
    public static final String SHOW_TYPE_LAYOUT_GROUP = "LayoutGroup";
    
    public static final String SHOW_TYPE_PRODUCT = "Product";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout.ShowType
     *
     * @mbggenerated
     */
    private String showtype;
    
    private String showtypeDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layout.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout.Id
     *
     * @return the value of layout.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout.Id
     *
     * @param id the value for layout.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout.Name
     *
     * @return the value of layout.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout.Name
     *
     * @param name the value for layout.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout.ShowType
     *
     * @return the value of layout.ShowType
     *
     * @mbggenerated
     */
    public String getShowtype() {
        return showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout.ShowType
     *
     * @param showtype the value for layout.ShowType
     *
     * @mbggenerated
     */
    public void setShowtype(String showtype) {
        this.showtype = showtype == null ? null : showtype.trim();
        if (Layout.SHOW_TYPE_CAROUSEL.equalsIgnoreCase(this.showtype)) {
           this.setShowtypeDisplay("图片轮播");
        } else if (Layout.SHOW_TYPE_ICONL.equalsIgnoreCase(this.showtype)) {
           this.setShowtypeDisplay("小图标");
        } else if (Layout.SHOW_TYPE_LAYOUT_GROUP.equalsIgnoreCase(this.showtype)) {
           this.setShowtypeDisplay("分组显示");
        } else if (Layout.SHOW_TYPE_PRODUCT.equalsIgnoreCase(this.showtype)) {
           this.setShowtypeDisplay("产品轮播");
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layout.Description
     *
     * @return the value of layout.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layout.Description
     *
     * @param description the value for layout.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

   @Override
   public Serializable getPK() {
      return id;
   }

   public String getShowtypeDisplay() {
      return showtypeDisplay;
   }

   public void setShowtypeDisplay(String showtypeDisplay) {
      this.showtypeDisplay = showtypeDisplay;
   }
}