package com.yiminwu.model;

public class ProductAttributeValue extends ProductAttributeValueKey {
   
    public ProductAttributeValue() {
       
    } 
    
    public ProductAttributeValue(Long productid, Integer attrid, String value) {
       super(productid, attrid);
       this.value = value;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_attr_value.Value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attr_value.Value
     *
     * @return the value of product_attr_value.Value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attr_value.Value
     *
     * @param value the value for product_attr_value.Value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}