package com.yiminwu.model;

public class ProductAttributeValueKey {
   
   public ProductAttributeValueKey() {
      
   }
   
   public ProductAttributeValueKey(Long productid, Integer attrid) {
      this.productid = productid;
      this.attrid = attrid;
      
   }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_attr_value.ProductId
     *
     * @mbggenerated
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_attr_value.AttrId
     *
     * @mbggenerated
     */
    private Integer attrid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attr_value.ProductId
     *
     * @return the value of product_attr_value.ProductId
     *
     * @mbggenerated
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attr_value.ProductId
     *
     * @param productid the value for product_attr_value.ProductId
     *
     * @mbggenerated
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attr_value.AttrId
     *
     * @return the value of product_attr_value.AttrId
     *
     * @mbggenerated
     */
    public Integer getAttrid() {
        return attrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attr_value.AttrId
     *
     * @param attrid the value for product_attr_value.AttrId
     *
     * @mbggenerated
     */
    public void setAttrid(Integer attrid) {
        this.attrid = attrid;
    }
}