package com.yiminwu.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Product implements BaseObject{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CodeNo
     *
     * @mbggenerated
     */
    private String codeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.BrandId
     *
     * @mbggenerated
     */
    private Integer brandid;
    
    private Integer classificationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ImgUrl
     *
     * @mbggenerated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Img1Url
     *
     * @mbggenerated
     */
    private String img1url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Img2Url
     *
     * @mbggenerated
     */
    private String img2url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Img3Url
     *
     * @mbggenerated
     */
    private String img3url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Img4Url
     *
     * @mbggenerated
     */
    private String img4url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Img5Url
     *
     * @mbggenerated
     */
    private String img5url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.SellCount
     *
     * @mbggenerated
     */
    private Integer sellcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ProductDetailPath
     *
     * @mbggenerated
     */
    private String productdetailpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ProductDetailMobilePath
     *
     * @mbggenerated
     */
    private String productdetailmobilepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.OnSale
     *
     * @mbggenerated
     */
    private Boolean onsale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Id
     *
     * @return the value of product.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Id
     *
     * @param id the value for product.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Name
     *
     * @return the value of product.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Name
     *
     * @param name the value for product.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CodeNo
     *
     * @return the value of product.CodeNo
     *
     * @mbggenerated
     */
    public String getCodeno() {
        return codeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CodeNo
     *
     * @param codeno the value for product.CodeNo
     *
     * @mbggenerated
     */
    public void setCodeno(String codeno) {
        this.codeno = codeno == null ? null : codeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Description
     *
     * @return the value of product.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Description
     *
     * @param description the value for product.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.BrandId
     *
     * @return the value of product.BrandId
     *
     * @mbggenerated
     */
    public Integer getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.BrandId
     *
     * @param brandid the value for product.BrandId
     *
     * @mbggenerated
     */
    public void setBrandid(Integer brandid) {
        this.brandid = brandid;
    }

    public Integer getClassificationid() {
      return classificationid;
   }

   public void setClassificationid(Integer classificationid) {
      this.classificationid = classificationid;
   }

   /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ImgUrl
     *
     * @return the value of product.ImgUrl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ImgUrl
     *
     * @param imgurl the value for product.ImgUrl
     *
     * @mbggenerated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Img1Url
     *
     * @return the value of product.Img1Url
     *
     * @mbggenerated
     */
    public String getImg1url() {
        return img1url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Img1Url
     *
     * @param img1url the value for product.Img1Url
     *
     * @mbggenerated
     */
    public void setImg1url(String img1url) {
        this.img1url = img1url == null ? null : img1url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Img2Url
     *
     * @return the value of product.Img2Url
     *
     * @mbggenerated
     */
    public String getImg2url() {
        return img2url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Img2Url
     *
     * @param img2url the value for product.Img2Url
     *
     * @mbggenerated
     */
    public void setImg2url(String img2url) {
        this.img2url = img2url == null ? null : img2url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Img3Url
     *
     * @return the value of product.Img3Url
     *
     * @mbggenerated
     */
    public String getImg3url() {
        return img3url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Img3Url
     *
     * @param img3url the value for product.Img3Url
     *
     * @mbggenerated
     */
    public void setImg3url(String img3url) {
        this.img3url = img3url == null ? null : img3url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Img4Url
     *
     * @return the value of product.Img4Url
     *
     * @mbggenerated
     */
    public String getImg4url() {
        return img4url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Img4Url
     *
     * @param img4url the value for product.Img4Url
     *
     * @mbggenerated
     */
    public void setImg4url(String img4url) {
        this.img4url = img4url == null ? null : img4url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Img5Url
     *
     * @return the value of product.Img5Url
     *
     * @mbggenerated
     */
    public String getImg5url() {
        return img5url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Img5Url
     *
     * @param img5url the value for product.Img5Url
     *
     * @mbggenerated
     */
    public void setImg5url(String img5url) {
        this.img5url = img5url == null ? null : img5url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Price
     *
     * @return the value of product.Price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Price
     *
     * @param price the value for product.Price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.SellCount
     *
     * @return the value of product.SellCount
     *
     * @mbggenerated
     */
    public Integer getSellcount() {
        return sellcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.SellCount
     *
     * @param sellcount the value for product.SellCount
     *
     * @mbggenerated
     */
    public void setSellcount(Integer sellcount) {
        this.sellcount = sellcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ProductDetailPath
     *
     * @return the value of product.ProductDetailPath
     *
     * @mbggenerated
     */
    public String getProductdetailpath() {
        return productdetailpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ProductDetailPath
     *
     * @param productdetailpath the value for product.ProductDetailPath
     *
     * @mbggenerated
     */
    public void setProductdetailpath(String productdetailpath) {
        this.productdetailpath = productdetailpath == null ? null : productdetailpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ProductDetailMobilePath
     *
     * @return the value of product.ProductDetailMobilePath
     *
     * @mbggenerated
     */
    public String getProductdetailmobilepath() {
        return productdetailmobilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ProductDetailMobilePath
     *
     * @param productdetailmobilepath the value for product.ProductDetailMobilePath
     *
     * @mbggenerated
     */
    public void setProductdetailmobilepath(String productdetailmobilepath) {
        this.productdetailmobilepath = productdetailmobilepath == null ? null : productdetailmobilepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.OnSale
     *
     * @return the value of product.OnSale
     *
     * @mbggenerated
     */
    public Boolean getOnsale() {
        return onsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.OnSale
     *
     * @param onsale the value for product.OnSale
     *
     * @mbggenerated
     */
    public void setOnsale(Boolean onsale) {
        this.onsale = onsale;
    }

   @Override
   public Serializable getPK() {
      return id;
   }
}