package com.yiminwu.model;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Transient;

@Entity
public class User implements BaseObject{
   
    public static String TYPE_ADMIN = "Admin";
    
    public static String TYPE_PROFILE = "Profile";
    
    public static String TYPE_BRAND_DISPLAY = "BrandDisplay";
    
    public static String TYPE_MALL = "Mall";
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Id
     *
     * @mbggenerated
     */
    @GeneratedValue
    @Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Passward
     *
     * @mbggenerated
     */
    private String passward;
    
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Type
     *
     * @mbggenerated
     */
    private String type;
    
    @Transient
    private String typeDisplay;
    
    @Transient
    private boolean updatePassward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Id
     *
     * @return the value of user.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Id
     *
     * @param id the value for user.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Name
     *
     * @return the value of user.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Name
     *
     * @param name the value for user.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Passward
     *
     * @return the value of user.Passward
     *
     * @mbggenerated
     */
    public String getPassward() {
        return passward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Passward
     *
     * @param passward the value for user.Passward
     *
     * @mbggenerated
     */
    public void setPassward(String passward) {
        this.passward = passward == null ? null : passward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Type
     *
     * @return the value of user.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Type
     *
     * @param type the value for user.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
        if (User.TYPE_ADMIN.equalsIgnoreCase(this.type)) {
           this.setTypeDisplay("Admin");
        } else if (User.TYPE_PROFILE.equalsIgnoreCase(this.type)) {
           this.setTypeDisplay("个人名片");
        } else if (User.TYPE_BRAND_DISPLAY.equalsIgnoreCase(this.type)) {
           this.setTypeDisplay("品牌展示");
        } else if (User.TYPE_MALL.equalsIgnoreCase(this.type)) {
           this.setTypeDisplay("商城");
        }
    }

    public String getTypeDisplay() {
      return typeDisplay;
   }

   public void setTypeDisplay(String typeDisplay) {
      this.typeDisplay = typeDisplay;
   }

   public boolean isUpdatePassward() {
      return updatePassward;
   }

   public void setUpdatePassward(boolean updatePassward) {
      this.updatePassward = updatePassward;
   }

   /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Code
     *
     * @return the value of user.Code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Code
     *
     * @param code the value for user.Code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Description
     *
     * @return the value of user.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Description
     *
     * @param description the value for user.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

   @Override
   public Serializable getPK() {
      return id;
   }

   public String getPhone() {
      return phone;
   }

   public void setPhone(String phone) {
      this.phone = phone;
   }
   
   public boolean isAdmin() {
      return User.TYPE_ADMIN.equalsIgnoreCase(this.getType());
   }
   
   public boolean isProfileType() {
      return User.TYPE_PROFILE.equalsIgnoreCase(this.getType());
   }
   
   public boolean isBrandDisplayType() {
      return User.TYPE_BRAND_DISPLAY.equalsIgnoreCase(this.getType());
   }
   
   public boolean isMallType() {
      return User.TYPE_MALL.equalsIgnoreCase(this.getType());
   }
}